### ISSUE TITLE
UI gets convoluted on a narrow screen

### ISSUE THREAD

**Issue by heralden** [intermine/bluegenes-tissue-expression-visualizer#6]
It would be great if we could stop the radio buttons from overlapping into their label, and perhaps set a minimum height for the cells in the expression graphs (so the tissue names don't mix into each other).

![2019-11-29-090409_723x420_scrot](https://user-images.githubusercontent.com/3865590/69857410-dca66a00-1287-11ea-8f52-f430194b2880.png)

**Comment by johasalinas** [comment]
I'm an Outreachy applicant, I would like to work on this. @uosl  Could you please assign me?

**Comment by heralden** [comment]
@jsnunki Sorry, it seems like there is already a PR for this (which embarrassingly for me, seems to not have been merged yet). I will let you know if there's still stuff that needs to be done for this issue, once I've reviewed #7.

**Comment by heralden** [comment]
The radio buttons are fixed now, but it seems the labels still overlap each other.

@jsnunki if you want, you can pick this up (or anyone else interested).

![2020-03-13-125220_653x390_scrot](https://user-images.githubusercontent.com/3865590/76622665-d764e680-6529-11ea-9502-d483e3c7b333.png)

**Comment by johasalinas** [comment]
@uosl Hi. Yes I'm interested. I take the opportunity to solve it.

**Comment by heralden** [comment]
@jsnunki Thank you! I assigned you to the issue.

**Comment by johasalinas** [comment]
Hi @uosl [This PR has multiple improvements :](https://github.com/intermine/bluegenes-tissue-expression-visualizer/pull/11) [UI Improvements #11](https://github.com/intermine/bluegenes-tissue-expression-visualizer/pull/11)
- The graphics now has a 100% width with a min-width of 700px (small screens) and a max-width of 1200px (Desktop screens).
- The graphics container has been centered.
- The controls are full clickable that means you can click the square instead of having to click the specific checkbox.

Note: The min-width of 700px was added because below that is not possible to avoid the overlap labels, this is an issue with the chart.js library itself.

Note: Looks like the tests are broken from before. This issue has been created to track: https://github.com/intermine/bluegenes-tissue-expression-visualizer/issues/10

![image](https://user-images.githubusercontent.com/5965987/76796540-f5517600-67cb-11ea-9d98-43468e903423.png)
![image](https://user-images.githubusercontent.com/5965987/76796527-eb2f7780-67cb-11ea-9a9d-64a45a83eead.png)
